DependencyInjection/DoctrineMongoDBExtension.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
This PR replace `setFactoryClass` and `setFactoryMethod` by `setFactory` method, according to Symfony deprecate rules.
`setFactory` was introduce on Symfony 2.6 (https://github.com/symfony/symfony/pull/9839) so this PR will break support of `symfony/dependency-injection` minor to 2.6.
But as you seems to be working on a new major version, this should not be a problem, isn't it?
Regards
=> Fix deprecated Factory definition

.travis.yml, composer.json
- add testing against newer PHP versions
- add testing on lowest composer deps (and fix them)
- switch to the faster container-based infrastructure
- keep the composer cache between builds
- use the mongo driver shipped by Travis for most builds (it is much newer, and already installed so faster)
=> Improve the Travis setup

CHANGELOG-3.0.md, composer.json
ODM 1.0.0 was released in August. It's about time we update that version constraint here.
=> Require stable ODM version

.travis.yml, CacheWarmer/HydratorCacheWarmer.php, CacheWarmer/ProxyCacheWarmer.php, Command/InfoDoctrineODMCommand.php, DependencyInjection/DoctrineMongoDBExtension.php, Form/Type/DocumentType.php, Logger/Logger.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/Form/Type/DocumentTypeTest.php, Tests/Logger/LoggerTest.php, composer.json
Supersedes #327, #310 and #285
Closes #325 
Thank you @tomasbro and @Soullivaneuh for getting started on this. I have taken your work for 3.0 compatibility and put it in here.
With the coming version (either 3.1 or 4.0, which is TBD) we are removing support for all Symfony versions older than 2.8 and in turn introduce compatibility with Symfony 3.0. We will tag one last release of the 3.0 line to have a 2.x version out that requires a stable version of doctrine/mongodb-odm. Please note that we are not providing any long term support for versions of our bundle that work with LTS versions of Symfony.
While there are a few open issues I'd like to look at in the coming days, getting this merged will allow people to use dev-master should they be using Symfony 3.0. I'm still hoping to get a …
=> Symfony 3.0 support

composer.json
While ODM does not officially support PHP 7 (due to the legacy MongoDB driver not being available), there are alternatives the people may use. This PR aims to allow those developers to use ODM with a polyfill for ext-mongo (e.g. mongofill, mongo-php-adapter) in PHP 7. This complements doctrine/mongodb-odm#1342.
=> Allow PHP 7 in composer.json

Form/Type/DocumentType.php, Tests/Form/Type/GuesserTestType.php
Hey!
This PR removes deprecatec calls which are only triger on Symfony 2.8. Since travis does not run the tests on this specific version, the regression has not been detected but travis reported it to me via https://travis-ci.org/php-lug/lug/jobs/107559855
=> Remove deprecated calls (Symfony 2.8 specific)

Resources/doc/index.rst
Once this PR is merged (and docs built) it'd be good idea to cross link it on http://symfony.com/doc/current/cookbook/doctrine/mongodb_session_storage.html
Closes #153
=> Add section on reusing connection

.travis.yml, Tests/Fixtures/Form/Category.php, Tests/Fixtures/Form/Document.php, Tests/Fixtures/Security/User.php, Tests/Fixtures/Validator/Document.php
While composer.json has allowed installing on PHP 7 for a while (given that the `ext-mongo` requirement is fulfilled), there were no tests for that platform. This PR adds alcaeus/mongo-php-adapter as polyfill to the PHP 7 version of the build matrix.
Note: due to a [bug with composer](https://github.com/composer/composer/issues/5030) the build step installing the polyfill is running with the `ignore-platform-reqs` flag. Once this bug is fixed the flag should be removed.
=> Add PHP 7 to the build matrix using polyfill

Mapping/Driver/XmlDriver.php, Mapping/Driver/YamlDriver.php, Resources/config/mongodb.xml, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/Mapping/Driver/AbstractDriverTest.php, Tests/Mapping/Driver/Fixtures/xml/Foo.Bar.mongodb.xml, Tests/Mapping/Driver/Fixtures/xml/Foo.mongodb.xml, Tests/Mapping/Driver/XmlDriverTest.php, Tests/Mapping/Driver/YamlDriverTest.php
Fix for https://github.com/doctrine/DoctrineMongoDBBundle/issues/357
Mention: I did not remove the deprecated status of the two mapping drivers from the bundle. Should I remove the deprecated messages too ?
=> Correction for mapping driver file extension

Command/CreateSchemaDoctrineODMCommand.php, Command/DropSchemaDoctrineODMCommand.php, Command/UpdateSchemaDoctrineODMCommand.php
I got quit a surprise in my deploy process when I found out the `doctrine:mongodb:schema:update` was always returning a success error code even when everything went wrong.
For exemple sometimes creating an index on a huge collection can reach my socket timeout ; so the indexes are deleted, not re-created, and I go live with a Mongo server going full CPU because some indexes are missing. 
Long story short, the issue is only in this bundle code. ODM return 255 when something goes bad: https://github.com/doctrine/mongodb-odm/blob/72ea5c74e7e4df6f22de14e8af71927db5110ae4/lib/Doctrine/ODM/MongoDB/Tools/Console/Command/Schema/UpdateCommand.php#L69 but this bundle does not always return the parent return value: https://github.com/doctrine/DoctrineMongoDBBundle/blob/97ac93c6058d53eb1dd59a1c296bbc8 …
=> Return the parent return value to keep the proper exit code

Tests/ContainerTest.php, Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php, Tests/DependencyInjection/Fixtures/config/yml/full.yml
It seems with Symfony 3.2 the `kernel.name` parameter is no longer automagically set in the container. To solve this, we declare it in all containers we're building. This PR also fix a deprecation warning about a duplicate key in the yaml configuration used in the tests.
Note: we might want to backport this PR to the 3.0 branch - might do that later.
=> Fix tests when running with Symfony 3.2

DataCollector/PrettyDataCollector.php, Tests/DataCollector/PrettyDataCollectorTest.php
The newly introduced loggable GridFS collection in doctrine/mongodb#274 is causing problems with the `PrettyDataCollector` as the data collector is not differentiating between the field `count` for a regular query and `count` (as number of affected documents) for a `storeFile`-query.
This PR aims to fix this issue and differentiate when building the log data.
=> Differentiate profiling count between GridFS and regular-count queries

DataCollector/PrettyDataCollector.php, Tests/DataCollector/PrettyDataCollectorTest.php
When no sort field was provided, the logged query could not be executed in the mongo shell because of a syntax error.
Before: `db.SomeDoc.find({ "field": "val" }).sort([ ]);`
After: `db.SomeDoc.find({ "field": "val" }).sort({ });`
=> Fixed empty sort query logging

DataCollector/PrettyDataCollector.php, Tests/DataCollector/PrettyDataCollectorTest.php
This builds on top of #390 and adds a bunch of `isset` checks around fields that are supposed to be in the `$log` array. In addition to that, it fixes the syntax for the count queries regarding limit and skip options.
=> Fix count queries in data collector

DependencyInjection/Configuration.php, Resources/config/schema/mongodb-1.0.xsd, Resources/doc/config.rst, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/Fixtures/config/xml/full.xml, Tests/DependencyInjection/Fixtures/config/yml/full.yml
If you use authentication on db-level, you need to specifiy a database name for the authentication. From MDB 2.6.x on it's this URI string parameter you need to set: https://docs.mongodb.com/manual/reference/connection-string/#urioption.authSource
Tested with:
mongodb/mongodb 1.0.1
doctrine/mongodb 1.4.0
doctrine/mongodb-odm 1.1.2
on PHP7 PHP 7.0.8-0ubuntu0.16.04.3 with MongoDB 2.6.10
=> Add missing authSource parameter to config

DependencyInjection/Configuration.php, DependencyInjection/DoctrineMongoDBExtension.php, Resources/config/schema/mongodb-1.0.xsd, Resources/doc/config.rst, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/Fixtures/config/xml/full.xml, Tests/DependencyInjection/Fixtures/config/yml/full.yml
Fixes #402.
This fixes an error when driver options were omitted in the configuration. For consistency with other options, this PR also renames the option to `driver_options` and `driver-options` in the Yaml and XML mappings respectively.
=> Fix driver option inconsistencies

Form/DoctrineMongoDBTypeGuesser.php, Tests/Fixtures/Form/Guesser.php, Tests/Form/Type/GuesserTestType.php, Tests/Form/Type/TypeGuesserTest.php
https://github.com/doctrine/mongodb-odm/pull/1073 added the `integer` and `bool` types, but these were not added to the type guesser. So, mapping a field with type `boolean` will yield a checkbox while using `bool` (which seems more logical especially when using scalar type hints) would yield a text input.
=> Add missing type names to type guesser

DataCollector/PrettyDataCollector.php, Tests/DataCollector/PrettyDataCollectorTest.php
=> Format aggregation queries in data collector

.travis.yml
This should fix segmentation faults with PHP 7.1, there's also no need to generate code coverage multiple times for the builds.
=> Disable code coverage generation for most builds

Command/LoadDataFixturesDoctrineODMCommand.php
Now bundle free applications(MicroKernelTrait based for example) could host fixtures directory in their kernel root.
=> Add kernel root directory to fixtures location paths

DependencyInjection/DoctrineMongoDBExtension.php, Resources/views/Collector/mongodb.html.twig
Playing around with a Symfony project created with Symfony Flex, I noticed that I got the error below everytime I try to access a profile in the profiler.
`The profiler template "DoctrineMongoDBBundle:Collector:mongodb.html.twig" for data collector "mongodb" does not exist.`
Changing the Twig notation fixed the problem.
=> Change Twig notation for the templates

Resources/doc/form.rst
The documented example didn't work with Symfony 3.x (leading to a new user who didn't understand why these examples didn't work on the Symfony support slack channel).
I fixed the examples that now work for sure with Symfony 2.8+ and Symfony 3. The removal of the `getName()` method may introduce an incompatibility with Symfony 2.7 (not sure about it), but I don't think this is a problem. Better make it work on Symfony 2.8+ rather than on 2.7 and 2.8 only.
=> Doc - Fix compatability with Symfony 3.x

Resources/doc/index.rst
Update installation instructions to contain only a dependency to ```doctrine/doctrine-odm-bundle```.
Related to #422
=> Updated installation instructions

Command/ShardDoctrineODMCommand.php
This patch adds `odm:schema:shard` command from DoctrineODM library.
See: http://docs.doctrine-project.org/projects/doctrine-mongodb-odm/en/latest/reference/sharding.html
=> Add Shard command from DoctrineODM

Resources/doc/config.rst
According to this doc :
http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers
The full list of caching driver is :
`array`, `apc`, `apcu`, `memcache`, `memcached`, `redis`, `wincache`, `zenddata` and `xcache`.
=> meta_cache_driver list update

CacheWarmer/ProxyCacheWarmer.php, Tests/CacheWarmer/ProxyCacheWarmerTest.php
Related to https://github.com/doctrine/mongodb-odm/pull/1628. The ProxyCacheWarmer still generates proxies for embedded documents, which causes errors if these are `final` and `doctrine/common` 2.8 is used.
@malarzm merging this down to `master` would force us to tag 3.4.0 since we've got at least one new feature (sharding command) in `master`. If you think we should fix this in 3.3, I'll create a support branch and backport the fix accordingly.
=> Exclude embedded documents from proxy generation

Tests/Command/LoadDataFixturesDoctrineODMCommandTest.php, Tests/DataCollector/PrettyDataCollectorTest.php, Tests/DataCollector/StandardDataCollectorTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php, Tests/Logger/LoggerTest.php, Tests/Mapping/Driver/AbstractDriverTest.php, Tests/TestCase.php, composer.json
I use the `PHPUnit\Framework\TestCase` notation instead of `PHPUnit_Framework_TestCase` while extending our TestCases. This will help us migrate to PHPUnit 6, that [no longer support snake case class names](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-6.0.md#changed-1).
I just need to bump PHPUnit version to [`^5.7`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#570---2016-12-02), that support this namespace.
=> Use PHPUnit\Framework\TestCase instead of PHPUnit_Framework_TestCase

Resources/config/mongodb.xml
It makes commands discoverable by Symfony 4
I used the new way of naming services using the FQCN accordingly to the future Symfony standard
=> Declare commands as services

DataCollector/StandardDataCollector.php, DependencyInjection/DoctrineMongoDBExtension.php, ManagerRegistry.php, Resources/config/mongodb.xml, Tests/DataCollector/StandardDataCollectorTest.php, Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
Based on deprecation warnings got from Symfony 3.4:
- The "**Symfony\Bridge\Doctrine\ManagerRegistry::setContainer()**" method is deprecated since version 3.4 and will be removed in 4.0. Inject a PSR-11 container using the constructor instead.
- The "**doctrine_mongodb**" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
- The "**doctrine_mongodb.odm.default_document_manager**" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
- Implementing …
=> Fix Symfony 4 BC breaks

Resources/config/mongodb.xml
This allows to implement services with autowiring like this, which is very handy.
```php
<?php
use Doctrine\Common\Persistence\ObjectManager;
class AcmeController
{
public function indexAction(Request $request, ObjectManager $om)
{
$hikes = $om->getRepository(Hike::class)->find();
// ...
}
}
```
=> Add aliases for autowiring

Form/DoctrineMongoDBTypeGuesser.php, Tests/Fixtures/Form/Guesser.php, Tests/Form/Type/GuesserTestType.php, Tests/Form/Type/TypeGuesserTest.php
Fix errors like "No mapping found for field 'plainPassword' in class 'App\Document\Administrator'."
=> Fix type guesser. Ignore field MappingException.

Resources/doc/config.rst
Fixes #241, #213.
Maybe we need to clean up our database options a bit - from `default_database`, the `database` option on the document manager config to the `db` option on the connection it can be confusing which option to set in which case. I'm open to suggestions on how to improve this.
=> Add database name to document manager docs

DependencyInjection/DoctrineMongoDBExtension.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
Fixes #432, cc @MatTheCat.
A connection may be in use for multiple document managers, so we can't reliably pick a configuration object for a connection based on a document manager name. This comes in addition to the fact that document managers are created after their connections and a connection doesn't know which document managers it is used for.
The changes could be construed as a BC break since some configuration service names change. If necessary, this can be resolved by generating an alias for the old name, marking that service as deprecated and dropping this behavior in 4.0.
For configurations where document manager and connection have the same name, no changes are visible outside of the container.
=> Fix configuration service names

Resources/doc/index.rst
I have added minimum documentation for guidance if you are using DoctrineMongoDBBundle in a Symfony 4 project like us.
=> Update index.rst with minimum documentation for Symfony 4 and autowiring

CHANGELOG-3.5.md
Note: waiting for the merge of #473, but this wraps up the 3.5.0 release by adding its changelog. All further features will wait for 4.0 which will also bring support for ODM 2.0.
=> Prepare changelog for 3.5.0

Resources/doc/config.rst, Resources/doc/form.rst, Resources/doc/index.rst
The DoctrineMongoDBBundle documentation is partly broken on symfony.com website: https://symfony.com/doc/current/bundles/DoctrineMongoDBBundle/index.html (see the "code-block php" appearing on the page).
This PR fixes these issues.
=> Fix RST syntax in documentation

Repository/ServiceDocumentRepository.php
The example was a fast copy/paste from the ORM version.
The ODM one is a little different.
Following https://github.com/doctrine/DoctrineMongoDBBundle/pull/473
=> Update example for repository autowired

DataCollector/CommandDataCollector.php
Changed exception interface 'Throwable' by the explicit class '\Exception' in order to fix https://github.com/doctrine/DoctrineMongoDBBundle/issues/488
=> Changed exception type

DependencyInjection/Configuration.php
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
more details:
symfony.com/blog/new-in-symfony-4-2-important-deprecations#deprecated-tree-builders-without-root-nodes
=> Deprecation fix for SF4.2

Command/DoctrineODMCommand.php, Command/InfoDoctrineODMCommand.php, Command/LoadDataFixturesDoctrineODMCommand.php, Resources/config/mongodb.xml, Tests/Command/LoadDataFixturesDoctrineODMCommandTest.php, Tests/ContainerTest.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php, Tests/ServiceRepositoryTest.php
This drops usage of `ContainerAwareCommand` in our commands, replacing it with `ContainerAwareInterface` instead. It also fixes build issues due to missing kernel parameters when testing against Symfony 4.2.
=> Fix more deprecations with Symfony 4.2

Command/TailCursorDoctrineODMCommand.php
Fixes #512. This was overlooked in #506, see also https://github.com/doctrine/DoctrineMongoDBBundle/pull/506#issuecomment-445417137.
=> Remove last usage of ContainerAwareCommand

DoctrineMongoDBBundle.php
Supersedes #511, fixes #510. This moves the fix to the 3.5 branch, which will then be merged down to master.
=> Fix clearstatcache call arguments

CacheWarmer/ProxyCacheWarmer.php, DependencyInjection/Configuration.php, DependencyInjection/DoctrineMongoDBExtension.php, Resources/config/mongodb.xml, Tests/CacheWarmer/ProxyCacheWarmerTest.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/TestCase.php, composer.json
Most changes are due to the proxy implementation change. We also use the new `CLIENT_TYPEMAP` constant from `DocumentManager` to stop replicating the `typeMap` option for the client.
=> Prepare bundle for ODM Beta 1

CacheWarmer/ProxyCacheWarmer.php, DoctrineMongoDBBundle.php
Because the dependency to `doctrine/common` is not in the `composer.json`.
=> Replace legacy Doctrine common code

Resources/doc/index.rst
The link to the instructions about using PHP7 points to the `latest` branch of the doc, which now references the 2.0 version. This version doesn't have the part about PHP7 so I forced the link to point to the doc of the 1.2 version.
=> Fix link to PHP7 usage instructions

DependencyInjection/Configuration.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/Form/Type/DocumentTypeTest.php, Tests/Form/Type/TypeGuesserTest.php, Tests/Mapping/Driver/AbstractDriverTest.php, composer.json, phpcs.xml.dist
Updated `composer.json` and set `doctrine/coding-standard` to `^6.0` 
Tested and fixed required changes via `phpcbf`
Please Note, I've disabled the Sniff `SlevomatCodingStandard.Classes.SuperfluousTraitNaming`  as it would require remove/refactoring of https://github.com/doctrine/DoctrineMongoDBBundle/blob/master/Repository/ServiceRepositoryTrait.php otherwise.
=> Updated doctrine/coding-standard to 6.0

DependencyInjection/DoctrineMongoDBExtension.php, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
Replacing tag `doctrine_mongodb.odm.event_listener` by `doctrine_mongodb.odm.event_subscriber`.
Following new Pull Requests from the next related issue: https://github.com/doctrine/mongodb-odm/issues/1993
=> Event subscriber

Command/LoadDataFixturesDoctrineODMCommand.php, DependencyInjection/Compiler/FixturesCompilerPass.php, DependencyInjection/DoctrineMongoDBExtension.php, DoctrineMongoDBBundle.php, Fixture/Fixture.php, Fixture/FixtureGroupInterface.php, Fixture/ODMFixtureInterface.php, Loader/SymfonyFixturesLoader.php, Loader/SymfonyFixturesLoaderInterface.php, Resources/config/mongodb.xml, Tests/Command/LoadDataFixturesDoctrineODMCommandTest.php, Tests/FixtureIntegrationTest.php, Tests/Fixtures/FooBundle/DataFixtures/DependentOnRequiredConstructorArgsFixtures.php, Tests/Fixtures/FooBundle/DataFixtures/OtherFixtures.php, Tests/Fixtures/FooBundle/DataFixtures/RequiredConstructorArgsFixtures.php, Tests/Fixtures/FooBundle/DataFixtures/WithDependenciesFixtures.php, Tests/Fixtures/FooBundle/FooBundle.php, Tests/ServiceRepositoryTest.php, composer.json
A first implementation, basically copy/paste from the fixturesbundle. 
Couple questions:
- Do we want to keep depending on the fixturesBundle or should we copy any files over so we can avoid the fixturesBundle which also installs the orm stuff which if you only use odm you don't need? (for example the FixtureGroupInterface)
- i based it on 3.5.3 as that is what i have locally, it would be nice if this could be included in 3.6, but not sure we can keep it backward compatible? Maybe if we keep fixtures/bundle options and keep their old implementation and if you provide an --autowire option it uses the new one? 
Thoughts?
Fixes #461
=> First implementation of symfony fixture loader + group support #461

Command/LoadDataFixturesDoctrineODMCommand.php
After merging #529, we can drop the legacy way of loading fixtures, which is by loading them from a directory or from bundles. Instead, we now only allow loading fixture services.
=> Drop file fixtures in favour of fixture services

APM/CommandLoggerRegistry.php, DependencyInjection/DoctrineMongoDBExtension.php, DoctrineMongoDBBundle.php, Resources/config/mongodb.xml, Tests/ContainerTest.php, Tests/FixtureIntegrationTest.php, composer.json
Fixes #563. Command subscribers were not properly registered - just adding a method call to the service definition is not enough.
To work around this, we add a command subscriber registry that is registered and unregistered when the bundle is booted and shut down. The registry proxies all calls to `register` and `unregister` to all registered subscribers. Since we don't have an interface for registrable command subscribers, I simply added `method_exists` checks to avoid fatal errors. We can still add an interface for such subscribers to the next release candidate for mongodb-odm and change the code to throw exceptions instead of silently skipping incompatible subscribers. Opinions @jmikola @malarzm?
=> Fix registration of command subscribers

.travis.yml, Repository/ContainerRepositoryFactory.php, Tests/DependencyInjection/Fixtures/config/yml/full.yml, Tests/Mapping/Driver/YamlDriverTest.php, Tests/TestCase.php
Apparently, some deprecations slipped through the cracks.
* Indirect notices are skipped - we generally can't fix these (think vendor code triggering deprecation notices)
* A single usage of a deprecated document repository class is ignored as fixing it requires bumping the minimum ODM version (which can't be done in a patch release)
* All other deprecations were fixed in the test suite.
=> Fix deprecations when running against ODM 1.3

.travis.yml
=> Removing travis allow failure for php7.4

Resources/doc/installation.rst
As true for mysql you can set up users in mongo to increase the security. When this is done one needs to provide the ODM driver with the information of username, password and authentication database (the database within the connection where the actual user is stored, which is different from the default database. I found after some intense research how it's done and found out it is not mentioned in the docs so I wanted to add it here were it belongs.
=> Authentication details

Resources/doc/first_steps.rst
=> Document service repositories

.travis.yml, DataCollector/CommandDataCollector.php, DependencyInjection/Configuration.php, README.markdown, Tests/DataCollector/CommandDataCollectorTest.php, composer.json
When adding compatibility with Symfony 5 in #602, we missed that Symfony 3.4 was still supported. Supporting 3.4 and 5.0 at the same time is not possible due to a method signature change in the data collector.
This PR fixes this issue by removing support for Symfony 3.4, which will be released as 4.1.0. This has the following implications:
* 4.0.* will no longer be supported. Users currently using Symfony 3.4 alongside ODM 2.0 should upgrade to Symfony 4.3 or newer as soon as possible.
* 4.1.* will be the new supported release for ODM 2
* 3.6.* still supports Symfony 3.4 and ODM 1.3 and will continue to do so until the end of life of ODM 1 is reached.
=> Fix wrong data collector signature

Resources/doc/first_steps.rst
We should use Doctrine\Bundle\MongoDBBundle\ManagerRegistry not Doctrine\Common\Persistence\ManagerRegistry
=> Fix ManagerRegistry namespace in documentation – first steps

.github/workflows/lint.yaml, Resources/doc/.doctor-rst.yaml, Resources/doc/config.rst, Resources/doc/form.rst, Resources/doc/index.rst
DOCtor-RST is a linting tool (which runs as GithubAction), which is used at symfony-docs, Sonata and EasyAdminBundle.
It checks the rst files for some specific conventions.
You can see it in Action here: https://github.com/symfony/symfony-docs/pull/13006/checks?check_run_id=414955239
We are using it since a few months for the symfony-docs and is developed by me 😄 
https://github.com/OskarStark/doctor-rst
=> Introduce DOCtor-RST

Resources/doc/config.rst, Resources/doc/console.rst, Resources/doc/cookbook/registration_form.rst, Resources/doc/events.rst, Resources/doc/first_steps.rst, Resources/doc/form_validation.rst, Resources/doc/index.rst, Resources/doc/installation.rst, Resources/doc/security_bundle.rst
This PR aims to modernize the bundle's documentation by resolving several opened issues.
- All URLs found in docs were checked for correctness and updated accordingly, new links were added where they could be helpful for newcomers (Form, Security, environment variables) - #538 
- Code examples no longer refer to Acme bundles; usage of Symfony Flex is recommended, configuration steps for projects not using Flex were updated for completeness - #536 
- code examples comply with Doctrine coding standard with few exceptions mentioned below  - #544
- some sentences were reworded to avoid belittling words - #539  and https://symfony.com/doc/current/contributing/documentation/standards.html
- a tip mentioning Replica Set option in connection string was added with link to relevant MongoDB docs …
=> Modernize documentation

DependencyInjection/DoctrineMongoDBExtension.php, EventSubscriber/EventSubscriberInterface.php, Resources/doc/events.rst
Totally copied from https://github.com/doctrine/DoctrineBundle/pull/1119 !
This is first step in order to split Doctriner EventSubscriber autoconfiguration and then resolve conflicts introduced in https://github.com/KnpLabs/DoctrineBehaviors/blob/master/src/Bundle/DependencyInjection/DoctrineBehaviorsExtension.php#L29
=> Add marker interface for event subscriber autoconfiguration

DependencyInjection/Configuration.php, DependencyInjection/DoctrineMongoDBExtension.php, ManagerConfigurator.php, Resources/config/schema/mongodb-1.0.xsd, Tests/DependencyInjection/AbstractMongoDBExtensionTest.php, Tests/DependencyInjection/ConfigurationTest.php, Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php, Tests/DependencyInjection/Fixtures/config/xml/odm_types.xml, Tests/DependencyInjection/Fixtures/config/yml/odm_types.yml, Tests/TestCase.php
Currently no problems with DM usage and doctrine:mongodb:generate:hydrators command.
It is possible to move method `\Doctrine\Bundle\MongoDBBundle\ManagerConfigurator::loadTypes` in separate service, but it is kinda looking OK in abstract Configurator.
=> Support custom types in configuration

Resources/doc/index.rst, Resources/doc/messenger.rst
=> Add section for Messenger integration

Resources/doc/config.rst
=> Section for custom types in configuration chapter

Command/ClearMetadataCacheDoctrineODMCommand.php, Command/CreateSchemaDoctrineODMCommand.php, Command/DropSchemaDoctrineODMCommand.php, Command/GenerateHydratorsDoctrineODMCommand.php, Command/GenerateProxiesDoctrineODMCommand.php, Command/InfoDoctrineODMCommand.php, Command/LoadDataFixturesDoctrineODMCommand.php, Command/QueryDoctrineODMCommand.php, Command/ShardDoctrineODMCommand.php, Command/TailCursorDoctrineODMCommand.php, Command/UpdateSchemaDoctrineODMCommand.php
This is just a fix of the previous PR https://github.com/doctrine/DoctrineMongoDBBundle/pull/641
More info by link https://github.com/doctrine/migrations/pull/839
=> Make commands lazily loaded
