DependencyInjection/Configuration.php
DependencyInjection/DoctrineMongoDBExtension.php
Resources/config/schema/mongodb-1.0.xsd
Resources/doc/config.rst
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/Fixtures/config/xml/full.xml
Tests/DependencyInjection/Fixtures/config/yml/full.yml

I'll try to go through other options and see if nothing else is missing, just found myself in need of these two right now

Added repository_factory and default_repository_class Configuration options

---

Resources/doc/index.rst

| Q             | A
| ------------- | ---
| Doc fix?      | yes
| New docs?     | no
| Applies to    | 3.0+
| Fixed tickets | #313

Fix #313: Outdated installation instructions pointing to @dev

---

Resources/doc/form.rst
Resources/doc/index.rst

more documentation cross link fixes

---

Resources/doc/config.rst

see [https://github.com/symfony/symfony-standard/issues/426](https://github.com/symfony/symfony-standard/issues/426)

doc: fix yaml syntax

---

Resources/views/Collector/mongodb.html.twig

This pull request will make the profiler debug toolbar extension more accurate to current symfony design

Changed toolbar design to 2.8+ style

---

Resources/config/schema/mongodb-1.0.xsd
Resources/doc/config.rst

Beside adding XML examples into docs I've also added missing attribute to XSD file and improved a bit yml config reference (closes #305)

Add XML configuration

---

.travis.yml
composer.json

Bumping PHP too since ODM requires 5.6

Bump requirements to ODM 1.1

---

DependencyInjection/Configuration.php
DependencyInjection/DoctrineMongoDBExtension.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
Tests/DependencyInjection/Fixtures/config/yml/full.yml

We could also expose option to set `PersistentCollectionGenerator` but I'm not sure if it's good idea

Expose configuration for PersistentCollectionFactory

---

Resources/doc/index.rst

Doc example update/fix

---

.travis.yml

Use prefer-dist for composer in travis build

---

Tests/DataCollector/PrettyDataCollectorTest.php

Passing test cases for https://github.com/doctrine/mongodb-odm/issues/898

Test formatting query with both sort and limit

---

Resources/doc/form.rst

Types inside form fields have been updated to classes

Updated form doc to Symfony 2.8 forms

---

Resources/doc/index.rst

Add a note on PHP 7

---

Resources/doc/form.rst

Sorry, there was one last thing to change in the documentation for compatibility with Symfony 2.8+, so here is an other PR (I couldn't squash commits as #415 is already merged).

Fix form creation for latest versions of Symfony

---

Resources/doc/index.rst

Update Installation chapter for Symfony 3.3+

---

Command/ShardDoctrineODMCommand.php

fix for bad namespace in ShardDoctrineODMCommand

---

Tests/Fixtures/Validator/Document.php
Tests/bootstrap.php

These should make the tests green again

Fix deprecations coming from ODM

---

.travis.yml
Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
Tests/DependencyInjection/ConfigurationTest.php
composer.json

Also removes the `ignore-platform-reqs` workaround for composer.json to fix other installation issues.

Test against PHP 7.2

---

DependencyInjection/Configuration.php
Resources/config/schema/mongodb-1.0.xsd
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/Fixtures/config/xml/full.xml
Tests/DependencyInjection/Fixtures/config/yml/full.yml

Replace authMechanism option value 'X509' by the proper value

---

Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
Tests/DependencyInjection/ConfigurationTest.php
Tests/DependencyInjection/Fixtures/config/xml/full.xml
Tests/DependencyInjection/Fixtures/config/xml/mongodb_service_simple_single_connection.xml
Tests/DependencyInjection/Fixtures/config/xml/mongodb_service_single_connection.xml
Tests/DependencyInjection/Fixtures/config/yml/full.yml
Tests/DependencyInjection/Fixtures/config/yml/mongodb_service_simple_single_connection.yml
Tests/DependencyInjection/Fixtures/config/yml/mongodb_service_single_connection.yml

This only changes the tests, the default configuration was not changed to not mess anything up.

Change memcache cache to memcached

---

Resources/config/mongodb.xml

Add missing service for command GenerateRepositoriesDoctrineODMCommand

---

Resources/doc/config.rst
Resources/doc/form.rst
Resources/doc/index.rst

This PR includes:
* #483
* #485 
* Updated information on PHP 7.
Commits may be squashed if needed.

[Doc] Documentation cleanup for DoctrineMongoDBBundle 4.0

---

DependencyInjection/DoctrineMongoDBExtension.php
Tests/DependencyInjection/AbstractMongoDBExtensionTest.php

Fix wrong capitalization of typeMap option

---

Repository/ServiceDocumentRepository.php
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Document/TestUnmappedDocument.php
Tests/DependencyInjection/Fixtures/Bundles/RepositoryServiceBundle/Repository/TestUnmappedDocumentRepository.php
Tests/ServiceRepositoryTest.php

ODM port of https://github.com/doctrine/DoctrineBundle/pull/825. This should help with issues like #504.

Better error message when missing document mapping

---

README.markdown

Updated versions to equal whats written in composer.json, as it was confusing to look at the Readme

Updated Readme.markdown to include current version constraints

---

. gitattributes

excluded useless files for production

added .gitattributes

---

DoctrineMongoDBBundle.php

Fixes #519 and https://github.com/doctrine/mongodb-odm/issues/1920.
@Rybbow could you give this a spin and let me know if this fixes your issue?

Fix registration of the proxy autoloader

---

Resources/doc/config.rst
Resources/doc/cookbook/registration_form.rst
Resources/doc/first_steps.rst

Use FQCN for services and documents

---

Command/LoadDataFixturesDoctrineODMCommand.php

Replace getRootDir by getProjectDir

---

DependencyInjection/Compiler/FixturesCompilerPass.php
DependencyInjection/DoctrineMongoDBExtension.php
Resources/config/mongodb.xml

Make sure doctrine/data-fixtures is really optional

---

Command/LoadDataFixturesDoctrineODMCommand.php

Remove mentions to removed option --fixtures

---

.travis.yml

This also fixes a rogue `allow_failures` that does not produce expected results.

Use travis jobs in build pipeline

---

Resources/doc/first_steps.rst
Resources/doc/index.rst

Fixes #571. @javiereguiluz is there any way to confirm whether the warnings are fixed or do you want me to just merge this to master and go from there?

Fix doc warnings

---

DependencyInjection/DoctrineMongoDBExtension.php
Tests/DependencyInjection/AbstractMongoDBExtensionTest.php

Supersedes #582.
cc @lljaworski.

Fix wrong driver options key

---

APM/PSRCommandLogger.php
CHANGELOG-4.0.md
Tests/ContainerTest.php
Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
Tests/DependencyInjection/DoctrineMongoDBExtensionTest.php
composer.json

Fix wrong interface inheritance in command logger

---

Resources/doc/installation.rst

As per the title, I should have merged this here instead of master.

Cherry pick of #592 to 4.0

---

.travis.yml
Command/InfoDoctrineODMCommand.php
Command/LoadDataFixturesDoctrineODMCommand.php
Command/TailCursorDoctrineODMCommand.php
DependencyInjection/DoctrineMongoDBExtension.php
Tests/Form/Type/DocumentTypeTest.php
Tests/Form/Type/TypeGuesserTest.php
composer.json

Fix symfony 5 compatibility

---

.travis.yml
Command/InfoDoctrineODMCommand.php
Command/LoadDataFixturesDoctrineODMCommand.php
Command/TailCursorDoctrineODMCommand.php
DependencyInjection/DoctrineMongoDBExtension.php
Resources/doc/first_steps.rst
Tests/Form/Type/DocumentTypeTest.php
Tests/Form/Type/TypeGuesserTest.php
composer.json

Release [4.0.1](https://github.com/doctrine/DoctrineMongoDBBundle/milestone/29)
4.0.1
=====
- Total issues resolved: **0**
- Total pull requests resolved: **2**
- Total contributors: **2**
Enhancement
-----------
- [602: Fix symfony 5 compatibility](https://github.com/doctrine/DoctrineMongoDBBundle/pull/602) thanks to @chalasr
Documentation
-------------
- [595: Document service repositories](https://github.com/doctrine/DoctrineMongoDBBundle/pull/595) thanks to @malarzm

Merge release 4.0.1 into master

---

DataCollector/PrettyDataCollector.php
Tests/DataCollector/PrettyDataCollectorTest.php

Fixes https://github.com/doctrine/DoctrineMongoDBBundle/issues/607
`countWithLimitOnlyInSimpleArray`... sounds a little weird, but I couldn't come up with something better.

Fix compatibility with php 7.4

---

Resources/doc/.doctor-rst.yaml
Resources/doc/index.rst

There were few things off that DOCtor-RST found after merging #613 so let's fix them before merging up

Fix failures found by DOCtor-RST

---

.travis.yml
Tests/DependencyInjection/AbstractMongoDBExtensionTest.php
Tests/FixtureIntegrationTest.php

fix compatibility with Symfony 5.1

---

Resources/doc/index.rst

Feels wrong at first, Or i am mistaken?

Improve clarity in docs

---

composer.json

The bundle is already compatible with it.
Closes #646

Allow persistence 2

---

composer.json

Release [4.2.1](https://github.com/doctrine/DoctrineMongoDBBundle/milestone/33)
4.2.1
=====
- Total issues resolved: **0**
- Total pull requests resolved: **1**
- Total contributors: **1**
Task
----
- [647: Allow persistence 2](https://github.com/doctrine/DoctrineMongoDBBundle/pull/647) thanks to @greg0ire

Merge release 4.2.1 into master

---

Command/LoadDataFixturesDoctrineODMCommand.php

This fixes the tag service name and removes reference to some nonexistent options.

Update load fixtures command description
